### ISSUE TITLE
offsetPosition error

### ISSUE THREAD

**Issue by ajp8164** [princejwesley/angular-circular-slider#12]
Hi -

Thank you for making a great control!  I'm using this circular slider with Ionic framework and am running into an error as described below.  The circular slider has been working and only appeared after placing the circular slider within an Ionic modal, <ion-modal-view>.

Perhaps you can provide some clues as to the root cause problem.  Thank you!

---

The error is as follows:

`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at $$ (http://localhost:3000/lib/angular.lib.js:31909:32)
    at Object.position (http://localhost:3000/lib/angular.lib.js:31958:15)
    at redrawShape (http://localhost:3000/lib/angular.lib.js:32662:32)
    at link (http://localhost:3000/lib/angular.lib.js:32627:7)
    at http://localhost:3000/lib/ionic.bundle.js:107:33
    at Y (http://localhost:3000/lib/ionic.bundle.js:107:89)
    at S (http://localhost:3000/lib/ionic.bundle.js:96:52)
    at g (http://localhost:3000/lib/ionic.bundle.js:88:384)
    at g (http://localhost:3000/lib/ionic.bundle.js:88:407) <circular-slider class="amount-slider acs-slider" shape="Circle" on-slide="c.onSlide" on-slide-end="c.onSlideEnd" radius="125" handle-dist-ratio="0.865" indicator-ball-ratio="0.28" min="c.min" max="c.max" value="c.amount">`

Here are the relevant calls in the stack:

In redrawShape:

`function redrawShape() {
        var component = buildComponents();
        var radius = getRadius();
        shapes[scope.shape].drawShape(component, radius);
        drawIndicatorBall(component, radius);

```
    var $$acs = $$(component.acs);
    var $$acsIndicator = $$(component.acsIndicator);
    cs.acsPosition = **$$acs.position()**;`
```

In Object.position:

When offsetParent() is called the dom object is populated but the offsetParent = null.

`function position() {
      var p = $$(**offsetParent()**);`

In $$:

`function $$(elem) {
    // only one element
    var dom = elem[0];
    var computedStyle = **window.getComputedStyle(dom, null);**`

In window.getComputedStyle() 'dom' is undefined.

My dom is as follows:

``` html
<div class="modal-backdrop active"><div class="modal-backdrop-bg"></div><div class="modal-wrapper" ng-transclude=""><ion-modal-view class="applet-modal modal animated zoomIn ng-enter active ng-enter-active"><!-- ngInclude: 'applets/paymentcs/views/index.html' --><div ng-include="'applets/paymentcs/views/index.html'"><div ng-controller="paymentCSController as c">
  <div class="applet-container" ng-style="{'background': c.applet.view.background}" style="background: rgb(247, 247, 247);">
      <ion-nav-bar class="bar bar-header bar-stable side='right' nav-bar-container" nav-bar-transition="ios">
            <ion-nav-buttons side="right" class="hide"></ion-nav-buttons>
      <div class="nav-bar-block" nav-bar="cached"><ion-header-bar class="bar bar-header bar-stable side='right'" align-title="center"><div class="title title-center header-item"></div><div class="buttons buttons-right header-item"><span class="right-buttons">
            <a class="button button-icon icon ion-close" ng-click="applet.close()"></a>
            </span></div></ion-header-bar></div><div class="nav-bar-block" nav-bar="active"><ion-header-bar class="bar bar-header bar-stable side='right'" align-title="center"><div class="title title-center header-item" style="left: 61px; right: 61px;"></div><div class="buttons buttons-right header-item"><span class="right-buttons">
            <a class="button button-icon icon ion-close" ng-click="applet.close()"></a>
            </span></div></ion-header-bar></div></ion-nav-bar>
      <div class="applet-content">
            <div style="position: absolute; float: right; right: 50%;" ng-click="c.setCurrency()">
                <div style="position: relative; float: right; right: -50%; top: 120px; z-index: 2; font-size: 32px; color: rgb(44, 62, 80);" ng-style="{'color': c.applet.view.csValueColor}" class="ng-binding">
                  25
                </div>
            </div>
            <div style="position: absolute; float: right; right: 50%;" ng-click="c.setCurrency()">
                <div style="position: relative; float: right; right: -50%; top: 160px; z-index: 2; font-size: 16px; color: rgb(44, 62, 80);" ng-style="{'color': c.applet.view.csValueColor}" class="ng-binding">
                  USD
                </div>
            </div>
            <div class="text-center" style="position: absolute; width: 100%; top: 20px">
                <style type="text/css" class="ng-binding">
                    .amount-slider .acs {
                      background: rgba(0,0,0,0);
                      border: 35px solid rgba(214, 214, 214, 0.5) !important;
                    }
                    .amount-slider .acs-value {
                      background: rgba(0,0,0,0);
                      border: 1px solid rgba(0,0,0,0);
                    }
                    .amount-slider .acs-indicator {
                      background: #909090;
                      border: none;
                    }
              </style>
                <circular-slider class="amount-slider acs-slider" shape="Circle" on-slide="c.onSlide" on-slide-end="c.onSlideEnd" radius="125" handle-dist-ratio="0.865" indicator-ball-ratio="0.28" min="c.min" max="c.max" value="c.amount">      <div class="acs-panel" style="border-width: 1px; border-radius: 251px;">        <div class="acs" style="width: 250px; height: 250px; border-radius: 250px; border-width: 1px;">          <div class="acs-value" ng-transclude="" style="width: 125px; height: 125px; font-size: 31.25px; top: 62.5px; left: 62.5px;">
                </div>        </div>        <div class="acs-indicator" style="width: 35px; height: 35px;">        </div>      </div>    </circular-slider>
            <div class="text-center m20t">
              <button class="button outline round tiny" ng-click="c.pay()" ng-style="{'background': c.applet.view.payButtonBackground, 'border': c.applet.view.payButtonBorder, 'color': c.applet.view.payButtonColor}" style="border: 1px solid rgb(165, 178, 191); color: rgb(133, 151, 167); background: none;">
                <span translate=""><span class="ng-binding">Donate now</span></span>
              </button>
            </div>
            </div>
        </div>
    </div>
</div></div></ion-modal-view></div></div>
```

**Comment by princejwesley** [comment]
can you try this?

``` js
    function offsetParent() {
      return angular.element(dom.offsetParent || dom.parentElement);
    }
```

slider is not hidden when this code is rendered, right?

**Comment by ajp8164** [comment]
Tried as suggested, not working.  The error is suppressed (since dom.parentElement is not null) but the math is all wrong and the indicator does not move.  The indicator is displayed in the upper left and the range (min..max) is cut down (I specify 10..100 and the presentation shows 32..52..32 on one complete path around the circle).  The parent element is acs-panel.

**Comment by princejwesley** [comment]
@ajp8164 I have no idea about ionic framework. If I can able to reproduce this issue, I can help you on that. (I assume that acs-panel class position set to 'relative')

**Comment by ajp8164** [comment]
I don't have a minimal sample that breaks, I may try to recreate the error by doing this.  I'm just putting the circular slider inside an Ionic modal.  Found this but it doesn't point to anything concrete yet - http://stackoverflow.com/questions/306305/what-would-make-offsetparent-null.

**Comment by ajp8164** [comment]
Ok.  I've noticed that 'element' comes in with no offsetParent which could be a root cause for the problem. 

https://github.com/princejwesley/angular-circular-slider/blob/master/src/js/angular-circular-slider.js#L728

**Comment by ajp8164** [comment]
I'm trying to setup a codepen for testing but it's not working.  See http://codepen.io/ajp8164/pen/pgZqpJ. Thanks!

**Comment by princejwesley** [comment]
@ajp8164 try [this](http://codepen.io/anon/pen/gPjZBE)

**Comment by ajp8164** [comment]
Great!  I added Ionic and placed the CS in a modal.  The behavior in [this pen](http://codepen.io/ajp8164/pen/XXBQaj) exactly replicates what I see in my app.

**Comment by princejwesley** [comment]
@ajp8164 Hope [this](http://codepen.io/anon/pen/xZJodK) helps.

**Comment by ajp8164** [comment]
You were a few minutes ahead of me ;-)  The problem is that the modal is not fully loaded at the time the circular-slider is rendered.  [This article](http://stackoverflow.com/questions/306305/what-would-make-offsetparent-null) states correctly that the offsetPosition is null if the document (in this case, the modal) is not finished loading.  [This pen](http://codepen.io/ajp8164/pen/XXBQaj) reflects what I implemented.  Thanks for your help on this!
