### ISSUE TITLE
Setting a negative min value behaves unexpectedly 

### ISSUE THREAD

**Issue by JMoli** [princejwesley/angular-circular-slider#13]
Setting a range of min = -100 to max=100 results in a slider that is from -100 to +200 . 

Try setting a negative value on the min here to reproduce: 
[http://codepen.io/ajp8164/pen/XXBQaj](codepen)

**Comment by princejwesley** [comment]
Demo has `max="200"`, set `max="max"`

**Comment by JMoli** [comment]
This does not resolve setting the min to a negative number

**Comment by JMoli** [comment]
This fixed the range, however now I am unable to set the default value to zero. Thoughts?
