### ISSUE TITLE
Two pointer indicator

### ISSUE THREAD

**Issue by rohamj** [princejwesley/angular-circular-slider#15]
Two pointer indicator is required, in order to slide start and end. 

Imagine if you have a price range, and u wanna select between 2,000 and 10,000

**Comment by princejwesley** [comment]
@rohamj it's not based on canvas/svg. I do have an implementation for such support. But I built that for one of my clients and I have to keep it private for 2 years as per our verbal agreement.  Look for canvas or svg based solution 👍
