### ISSUE TITLE
two sliders?

### ISSUE THREAD

**Issue by netmonster01** [princejwesley/angular-circular-slider#18]
Hello,

Is it possible to host two sliders on the same page? I tried to create a scope var called $scope.speed and bind it one of the sliders and it will only show the value if I use a scope var called "value".

Plunker
https://plnkr.co/edit/KUGMdN8aevMoj4D1oeVb?p=preview

Thanks,
KC

**Comment by princejwesley** [comment]
@netmonster01 Use `value` inside `<tag>{{value}}</tag>` `$scope` binding can be anything

https://plnkr.co/edit/0ufQshIBas8W4YooKIHx?p=preview

**Comment by netmonster01** [comment]
Oh, got it now. I was thinking the label should be the same as the $scope.

Thanks for the quick reply.
