### ISSUE TITLE
Disabling slider

### ISSUE THREAD

**Issue by alexanderjareno** [princejwesley/angular-circular-slider#3]
Hi,

I'm new to angular, and I'm using your slider for a university project. I would like to disable the slider when a button is pressed. I've tried using ng-disabled, but could not get it to work. Do you know if there's another way for your slider, or is that a feature which is not implemented?

Regards,
Alex

**Comment by senthilporunan** [comment]
Hi Alex,

Thanks for contacting us. We have not implemented this feature. We will add this as feature in couple of days based upon our availability.

Thanks,
Senthil.

**Comment by princejwesley** [comment]
`disabled` is the property name. [Added](https://github.com/princejwesley/angular-circular-slider/commit/f73c56a1ba78033e88559ea16403bc3d6ae0b9f3) to [V0.1.1](https://github.com/princejwesley/angular-circular-slider/releases/tag/V0.1.1)

**Comment by alexanderjareno** [comment]
Thank you, we have now implemented the disabling function and it is working good!
Regards,
Alex
