### ISSUE TITLE
Touch property is not functioning properly

### ISSUE THREAD

**Issue by alexanderjareno** [princejwesley/angular-circular-slider#4]
Hello again,

Another question, is your slider touch-slide-compatible from start, or do I have do do something to get that to work? I have set touch='true', but it doesn't seem to make a difference whether it is set true or false, I still can't touch slide it, only press to move the slider to different locations.

Best regards!
Alex

**Comment by senthilporunan** [comment]
Hi Alex, 

We have already implemented touch functionality in it. We did unit testing and it worked fine. Could you please share your configuration based on that we will fix this one soon.

Regds,
Senthil.

**Comment by princejwesley** [comment]
Fixed [it](https://github.com/princejwesley/angular-circular-slider/commit/ca335104c5d65758408c160f47738d1ae8a81e8c).

**Comment by alexanderjareno** [comment]
Thank you very much, the touch works fine now!
