### ISSUE TITLE
re initializing the directive error

### ISSUE THREAD

**Issue by meezyart** [princejwesley/angular-circular-slider#6]
error reads
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

**Comment by senthilporunan** [comment]
Code fixed in latest version (v0.1.3). Please reopen the bug if you are facing any issue on it.

**Comment by meezyart** [comment]
THanks brother .. can I get the min version too?

**Comment by princejwesley** [comment]
Done
