### ISSUE TITLE
[SOLVED] Problem with ionic. Slider is 0px height.

### ISSUE THREAD

**Issue by connesso** [princejwesley/angular-circular-slider#8]
Hi and thank you for your great job!

The slider is totally flat when used with ionic.
![bug_slider](https://cloud.githubusercontent.com/assets/9828883/9005833/d68f809c-3781-11e5-9420-0e05648b01a8.png)
![bug-slider-png](https://cloud.githubusercontent.com/assets/9828883/9005835/d69157dc-3781-11e5-9d46-900179354241.png)
![bug-slider-png2](https://cloud.githubusercontent.com/assets/9828883/9005834/d68faffe-3781-11e5-9363-3b212ccf9501.png)

**Comment by princejwesley** [comment]
@connesso Set `shape='Half Circle'`.

Check console for error something like this:

> Unsupported shape: half-circle `<circular-slider class="my-slider ng-isolate-scope" shape="half-circle"   touch="true" animate="true" on-slide="onSlide" on-slide-end="onSlideEnd" min="min" max="200" value="value">`

**Comment by connesso** [comment]
yes thank you for your speed answer!
